name: Deploy to Sandbox

on:
  push:
    branches:
      - 'feature/**'
      - 'ft/**'

jobs:
  pr-checks:
    uses: ./.github/workflows/pr_checks.yaml
      
  sandbox-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Sandbox
        run: |
          echo "Deploying to Sandbox environment"
          echo "Branch: ${{ github.ref }}"

      - name: Set up environment
        run: echo "API_TOKEN_GITHUB=${{ secrets.API_TOKEN_GITHUB }}" >> $GITHUB_ENV

      - name: Run Ansible 
        run: |
          echo "Running Ansible"
          ansible-playbook ansible/playbook.yaml
        env: 
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}