name: Deploy to Sandbox

on:
  push:
    branches:
      - 'feature/**'
      - 'ft/**'

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PR Checks
        uses: ./.github/workflows/pr_checks
      
  sandbox-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Sandbox
        run: |
          echo "Deploying to Sandbox environment"
          echo "Branch: ${{ github.ref }}"
