name: Deploy to Sandbox

on:
  push:
    branches:
      - 'feature/**'

jobs:
  sandbox-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check and Install Ansible
        run: |
          if ! command -v ansible &> /dev/null
          then
              echo "Ansible not found. Installing Ansible..."
              sudo apt update
              sudo apt install -y ansible
          else
              echo "Ansible is already installed"
          fi

      - name: Run Ansible 
        run: |
          echo "Running Ansible"
          ansible-playbook ansible/playbook.yaml

