name: Deploy to Production

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  pr-checks:
    uses: ./.github/workflows/pr_checks.yaml
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Production
        run: |
          echo "Deploying to Production environment"
          echo "Tag: ${{ github.ref }}"
