name: Deploy to Sandbox

on:
  push:
    branches:
      - 'feature/**'
      - 'ft/**'

jobs:
  pr-checks:
    uses: ./.github/workflows/pr_checks.yaml
      
  sandbox-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Sandbox
        run: |
          echo "Deploying to Sandbox environment"
          echo "Branch: ${{ github.ref }}"

      - name: For Ansible Permissions
        run: |
          sudo apt update
          sudo apt-get install acl

      - name: Run Ansible 
        run: |
          echo "Running Ansible"
          ansible-playbook ansible/playbook.yaml