name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PR Checks
        run: |
          echo "Running checks for Pull Request"
          echo "PR: ${{ github.event.pull_request.number }}"

      - name: Check and Install Terraform
        run: |
          if ! command -v terraform &> /dev/null
          then
              echo "Terraform not found. Installing Terraform..."
              sudo apt update
              sudo apt install -y terraform
          else
              echo "Terraform is already installed"
          fi
      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: v0.52.0

      - name: Show version
        run: tflint --version

      - name: Run TFLint
        run: |
          echo "Running TFLint"
          #tflint

      - name: Check and Install Ansible
        run: |
          if ! command -v ansible &> /dev/null
          then
              echo "Ansible not found. Installing Ansible..."
              sudo apt update
              sudo apt install -y ansible
          else
              echo "Ansible is already installed"
          fi
      - name: Check and Install Ansible Lint
        run: |
          if ! command -v ansible-lint &> /dev/null
          then
              echo "Ansible Lint not found. Installing Ansible Lint..."
              pip install ansible-lint
          else
              echo "Ansible Lint is already installed"
          fi

      - name: Run Ansible Lint
        run: |
          echo "Running Ansible Lint"
          #ansible-lint

