name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PR Checks
        run: |
          echo "Running checks for Pull Request"
          echo "PR: ${{ github.event.pull_request.number }}"
      
      - name: Check and Install Ansible
        run: |
          if ! command -v ansible &> /dev/null
          then
              echo "Ansible not found. Installing Ansible..."
              sudo apt update
              sudo apt install -y ansible
          else
              echo "Ansible is already installed"
          fi

      - name: Run Ansible Lint
        run: |
          echo "Running Ansible Lint"
          ansible-lint 